--
-- PostgreSQL database dump
--

\restrict ta7XlzGyMhcfHJYUp5EMoKVLdRsavufkbaKn5Nd6iqQD5qM1quZ2DdZ5oTbDQ1i

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: books; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.books (
    id bigint NOT NULL,
    author character varying(255) NOT NULL,
    isbn character varying(255) NOT NULL,
    published_date date,
    title character varying(255) NOT NULL
);


--
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: books; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.books (id, author, isbn, published_date, title) FROM stdin;
1	Robert C. Martin	9780132350884	2008-08-01	Clean Code
2	Robert C. Martin	9780134494166	2017-09-10	Clean Architecture
3	Martin Fowler	9780134757599	2018-11-19	Refactoring
4	Andrew Hunt & David Thomas	9780135957059	2019-09-01	The Pragmatic Programmer
5	Erich Gamma et al.	9780201633610	1994-10-21	Design Patterns
6	Eric Freeman	9781492078005	2020-12-01	Head First Design Patterns
7	Joshua Bloch	9780134685991	2018-01-06	Effective Java
8	Craig Walls	9781617297571	2022-01-01	Spring in Action
9	Thomas H. Cormen	9780262033848	2009-07-31	Introduction to Algorithms
\.


--
-- Name: books_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.books_id_seq', 12, true);


--
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- Name: books ukkibbepcitr0a3cpk3rfr7nihn; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT ukkibbepcitr0a3cpk3rfr7nihn UNIQUE (isbn);


--
-- PostgreSQL database dump complete
--

\unrestrict ta7XlzGyMhcfHJYUp5EMoKVLdRsavufkbaKn5Nd6iqQD5qM1quZ2DdZ5oTbDQ1i

